---

# ---------------------------------------------------------------------------------------
#   Deploy UCS Domain Profile for Cisco UCS FI Domain. Profile is derived from a
#   Domain Profile Template, then assigned and deployed on FIs
# ---------------------------------------------------------------------------------------

- name: Define anchor for Intersight API login info
  ansible.builtin.set_fact:
      api_info: &api_info
        api_private_key: "{{ intersight_api_private_key }}"
        api_key_id: "{{ intersight_api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"

# - name: Configure domain profile for UCS FI domain - derive, assign and deploy 
#   block: 
#     - name: Verify parameters referenced in following task(s)
#       debug:
#         var: fi_a_domain_profile_template
#           # fi_b_domain_profile_template
#           # domain_profile_template 
#       when: configure_openshift == 'true'

#     - name:  Get Moid for UCS FI-A
#       cisco.intersight.intersight_rest_api:
#         <<: *api_info
#         resource_path: /network/Elements
#         query_params:
#           $filter: "Serial eq '{{ fi_a_sn }}'"
#       register: fi_a_switch_profile
    
#     - name: Verify parameters referenced in following task(s)
#       debug:
#         var: fi_a_switch_profile

#     - name:  Get Moid for UCS FI-B
#       cisco.intersight.intersight_rest_api:
#         <<: *api_info
#         resource_path: /network/Elements
#         query_params:
#           $filter: "Serial eq '{{ fi_b_sn }}'"
#       register: fi_b_switch_profile

#     - name: Verify parameters referenced in following task(s)
#       debug:
#         var: fi_b_switch_profile

#     - name: Derive domain profile from template and assign it to UCS FI domain - USE WITH CARE!!!
#       cisco.intersight.intersight_rest_api:
#         <<: *api_info
#         resource_path: /bulk/MoCloners
#         query_params:
#           $filter: "Name eq '{{ name_of_ucs_domain_profile }}'"
#         api_body: {
#           Sources: [
#             {
#               "Moid": "{{domain_profile_template.api_response.Moid}}",
#               "ObjectType": "fabric.SwitchClusterProfileTemplate"
#             }
#           ],
#           Targets: [
#             {
#               "Name": "{{name_of_ucs_domain_profile}}",
#               "ObjectType": "fabric.SwitchClusterProfile",
#               "ClusterAssignments": [
#                   {
#                       "SourceSwitchProfileOrTemplateName": "{{name_of_fi_a_domain_profile_template}}",
#                       "NetworkElement": {
#                           "ObjectType": "network.Element",
#                           "Moid": "{{fi_a_switch_profile.api_response.Moid}}"
#                       }
#                   },
#                   {
#                       "SourceSwitchProfileOrTemplateName": "{{name_of_fi_b_domain_profile_template}}",
#                       "NetworkElement": {
#                           "ObjectType": "network.Element",
#                           "Moid": "{{fi_b_switch_profile.api_response.Moid}}"
#                       }
#                   }
#               ],
#               "Organization": {
#                   "Moid": "{{intersight_org.api_response.Moid}}",
#                   "ObjectType": "organization.Organization"
#               },
#               "Description": "{{description_of_ucs_domain_profile}}",
#               "Tags": [
#                   {
#                       "Key": "Provisioned by:",
#                       "Value": "Intersight-Ansible"
#                   },
#                   {
#                       "Key": "Project:",
#                       "Value": "{{prefix}}"
#                   }
#               ]
#             }
#           ]
#         }
#         state: present  
#       register: domain_profile
    
#     - name: Verify parameters referenced in following task(s)
#       debug:
#         var: domain_profile

    

































































