# ###################################################################################################
#                                           Storage
# ###################################################################################################
# ONTAP Cluster Management IP. List only one ONTAP cluster IP.
[ontap]
placeholder-ontap_cluster_mgmt_ip

# ###################################################################################################
#                                           Compute
# ###################################################################################################
# The playbooks are used to create server profile template from which
# server profiles are derived manually by the end user.

# Note: at least one host must be present for intersight_update_inventory.yml to work
# You can execute update_all_inventory.yml playbook to dynamically update server information in this file.
#

#####
[Dynamic_Inventory]
placeholder-cisco_imm_servers-do-not-delete

# This group will be created by intersight_update_inventory.yml - defining it is optional.
[cisco_imm_servers:children]
Dynamic_Inventory

# [intersight_api_host]
# localhost ansible_connection=local

[cisco_intersight:children]
# intersight_api_host
cisco_imm_servers
#####

[cisco_ucsm_servers]
# Placeholder for UCSM managed servers

[cisco_compute:children]
cisco_intersight
cisco_ucsm_servers

# ###################################################################################################
#                                           ALL
# ###################################################################################################

[all:children]
cisco_compute
netapp_storage
# cisco_network_nxos
# cisco_network_san

; [all:vars]
; ; configure_fc="false"
; ; configure_iscsi="true"
; ; configure_fc_nvme="false"
